"""add soft delete to users and tasks

Revision ID: 25c4f153ef1d
Revises: 2011afb53a5e
Create Date: 2026-02-20 09:10:43.999522

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c4f153ef1d'
down_revision: Union[str, Sequence[str], None] = '2011afb53a5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tasks_deleted_at'), 'tasks', ['deleted_at'], unique=False)
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_column('users', 'deleted_at')
    op.drop_index(op.f('ix_tasks_deleted_at'), table_name='tasks')
    op.drop_column('tasks', 'deleted_at')
    # ### end Alembic commands ###
